version: '3'
services:
  nginx:
    image: nginx
    # build: .
    ports:
      - "3000:80"
    volumes:
      - "./conf.d/:/etc/nginx/conf.d"
    links:
      - node
  node:
    image: node
    # build: .
    volumes:
      - ./src/:/src
    working_dir: /src
    # Nginxで設定するためにhostnameを指定する
    hostname: node
    ports:
      - "8080:8080"
    command: [sh, -c, npm install && npm start]
